// Application constants

export const SITE_NAME = 'eSports Hub';
export const SITE_DESCRIPTION = 'The ultimate eSports competition platform';

export const NAVIGATION_ITEMS = [
  { href: '/dashboard', label: 'Dashboard', icon: 'LayoutDashboard' },
  { href: '/torneos', label: 'Torneos', icon: 'Trophy' },
  { href: '/equipos', label: 'Equipos', icon: 'Users' },
  { href: '/tienda', label: 'Tienda', icon: 'ShoppingCart' },
  { href: '/usuario', label: 'Perfil', icon: 'User' },
];

export const MOCK_GAMES = [
  { id: '1', name: 'League of Legends', icon: '🎮', tournaments: 24 },
  { id: '2', name: 'Counter-Strike 2', icon: '🔫', tournaments: 18 },
  { id: '3', name: 'Valorant', icon: '⚔️', tournaments: 15 },
  { id: '4', name: 'Dota 2', icon: '🎯', tournaments: 12 },
];

export const MOCK_GAMES_WITH_DETAILS = [
  {
    id: '1',
    name: 'League of Legends',
    icon: '🎮',
    tournaments: 24,
    platforms: ['PC'],
    gameModes: ['5v5', 'Solo/Duo', 'Flex'],
  },
  {
    id: '2',
    name: 'Counter-Strike 2',
    icon: '🔫',
    tournaments: 18,
    platforms: ['PC'],
    gameModes: ['5v5', '1v1'],
  },
  {
    id: '3',
    name: 'Valorant',
    icon: '⚔️',
    tournaments: 15,
    platforms: ['PC'],
    gameModes: ['5v5', '1v1'],
  },
  {
    id: '4',
    name: 'Dota 2',
    icon: '🎯',
    tournaments: 12,
    platforms: ['PC'],
    gameModes: ['5v5', 'Solo/Duo'],
  },
];

export const MOCK_TOURNAMENTS = [
  {
    id: '1',
    name: 'World Championship 2024',
    game: 'League of Legends',
    prizePool: 1000000,
    startDate: '2024-12-15',
    endDate: '2024-12-22',
    status: 'upcoming' as const,
    participants: 16,
    maxParticipants: 16,
  },
  {
    id: '2',
    name: 'Major Spring Split',
    game: 'Valorant',
    prizePool: 500000,
    startDate: '2024-12-10',
    endDate: '2024-12-15',
    status: 'live' as const,
    participants: 24,
    maxParticipants: 32,
  },
  {
    id: '3',
    name: 'International Finals',
    game: 'Dota 2',
    prizePool: 750000,
    startDate: '2024-12-08',
    endDate: '2024-12-12',
    status: 'finished' as const,
    participants: 8,
    maxParticipants: 8,
  },
];

export const MOCK_TEAMS = [
  {
    id: '1',
    name: 'Shadow Phoenix',
    logo: '🔥',
    game: 'League of Legends',
    members: 5,
    wins: 34,
    losses: 12,
    region: 'LAS',
    founded: '2022-03-15',
  },
  {
    id: '2',
    name: 'Cyber Ninjas',
    logo: '🥷',
    game: 'Valorant',
    members: 5,
    wins: 28,
    losses: 15,
    region: 'NA',
    founded: '2021-07-20',
  },
  {
    id: '3',
    name: 'Digital Titans',
    logo: '🦾',
    game: 'Dota 2',
    members: 6,
    wins: 22,
    losses: 18,
    region: 'EU',
    founded: '2020-11-10',
  },
  {
    id: '4',
    name: 'Neon Knights',
    logo: '⚔️',
    game: 'Counter-Strike 2',
    members: 5,
    wins: 31,
    losses: 14,
    region: 'EU',
    founded: '2023-01-05',
  },
  {
    id: '5',
    name: 'Frost Legion',
    logo: '❄️',
    game: 'League of Legends',
    members: 5,
    wins: 26,
    losses: 16,
    region: 'LATAM',
    founded: '2022-08-12',
  },
  {
    id: '6',
    name: 'Thunder Strike',
    logo: '⚡',
    game: 'Valorant',
    members: 5,
    wins: 29,
    losses: 13,
    region: 'KR',
    founded: '2022-05-30',
  },
  {
    id: '7',
    name: 'Apex Legends',
    logo: '👑',
    game: 'Dota 2',
    members: 6,
    wins: 25,
    losses: 17,
    region: 'SEA',
    founded: '2021-02-18',
  },
  {
    id: '8',
    name: 'Quantum Force',
    logo: '⚛️',
    game: 'Counter-Strike 2',
    members: 5,
    wins: 32,
    losses: 11,
    region: 'NA',
    founded: '2023-06-22',
  },
];

export const MOCK_CREDIT_PACKAGES = [
  {
    id: '1',
    credits: 1,
    price: 1.0,
  },
  {
    id: '2',
    credits: 3,
    price: 2.25,
    savings: 25,
  },
  {
    id: '3',
    credits: 5,
    price: 3.75,
    savings: 25,
  },
  {
    id: '4',
    credits: 7,
    price: 5.0,
    savings: 29,
  },
  {
    id: '5',
    credits: 10,
    price: 7.5,
    savings: 25,
    highlighted: true,
  },
  {
    id: '6',
    credits: 15,
    price: 10.0,
    savings: 33,
  },
];

export const MOCK_MEMBERSHIP_TIERS = [
  {
    id: '1',
    name: 'Gratis',
    duration: 0,
    durationUnit: 'month' as const,
    price: 0,
    benefits: [
      'Acceso a competiciones gratuitas',
      'Desafía a otros jugadores a apostar partidos',
      'Desafía a otros jugadores a partidas de XP',
      'Benefíciese de premios con pago instantáneo',
    ],
  },
  {
    id: '2',
    name: 'Membresía 1 Mes',
    duration: 1,
    durationUnit: 'month' as const,
    price: 5.99,
    benefits: [
      'Todo desde la membresía gratuita',
      'Apuestas sin comisiones',
      'Entrada gratuita a los torneos ELITE',
      'Avatares personalizados',
      'Personalización de la página del equipo',
      'Personalización de la página de perfil',
    ],
  },
  {
    id: '3',
    name: 'Membresía 3 Meses',
    duration: 3,
    durationUnit: 'months' as const,
    price: 12.99,
    originalPrice: 17.97,
    savings: 28,
    benefits: [
      'Todo desde la membresía gratuita',
      'Apuestas sin comisiones',
      'Entrada gratuita a los torneos ELITE',
      'Avatares personalizados',
      'Personalización de la página del equipo',
      'Personalización de la página de perfil',
    ],
  },
  {
    id: '4',
    name: 'Membresía 6 Meses',
    duration: 6,
    durationUnit: 'months' as const,
    price: 24.99,
    originalPrice: 35.94,
    savings: 30,
    benefits: [
      'Todo desde la membresía gratuita',
      'Apuestas sin comisiones',
      'Entrada gratuita a los torneos ELITE',
      'Avatares personalizados',
      'Personalización de la página del equipo',
      'Personalización de la página de perfil',
    ],
  },
  {
    id: '5',
    name: 'Membresía 12 Meses',
    duration: 12,
    durationUnit: 'months' as const,
    price: 49.99,
    originalPrice: 71.88,
    savings: 30,
    highlighted: true,
    benefits: [
      'Todo desde la membresía gratuita',
      'Apuestas sin comisiones',
      'Entrada gratuita a los torneos ELITE',
      'Avatares personalizados',
      'Personalización de la página del equipo',
      'Personalización de la página de perfil',
    ],
  },
];

export const MOCK_SERVICES = [
  {
    id: '1',
    name: 'Cambio de Nickname',
    description: 'Cambia tu nombre de usuario en la plataforma',
    price: 3.99,
    icon: '✏️',
    category: 'profile' as const,
  },
  {
    id: '2',
    name: 'Récord de Juego Reiniciado',
    description: 'Reinicia tu histórico de partidas jugadas',
    price: 5.99,
    icon: '🔄',
    category: 'stats' as const,
  },
  {
    id: '3',
    name: 'Estadísticas Reiniciadas',
    description: 'Reinicia todas tus estadísticas de juego',
    price: 3.99,
    icon: '📊',
    category: 'stats' as const,
  },
  {
    id: '4',
    name: 'Reclamar Nombre Inactivo',
    description: 'Contacta con soporte para reclamar un nombre inactivo',
    price: 9.99,
    icon: '👑',
    category: 'support' as const,
  },
];

export const MOCK_USER_PROFILES = {
  ProGamer: {
    id: '1',
    nickname: 'ProGamer',
    avatar: '/placeholder-user.jpg',
    bio: 'Competitive eSports player | League of Legends & Valorant enthusiast',
    level: 42,
    totalXP: 125000,
    balance: 2450.50,
    totalEarnings: 15230.00,
    joinDate: '2022-01-15',
    gameStats: [
      {
        id: '1',
        game: 'League of Legends',
        wins: 156,
        losses: 89,
        winRate: 63.7,
        totalMatches: 245,
        bestRank: 'Challenger',
        currentRank: 'Grandmaster',
        totalHours: 2340,
      },
      {
        id: '2',
        game: 'Valorant',
        wins: 234,
        losses: 112,
        winRate: 67.6,
        totalMatches: 346,
        bestRank: 'Radiant',
        currentRank: 'Radiant',
        totalHours: 3120,
      },
      {
        id: '3',
        game: 'Counter-Strike 2',
        wins: 89,
        losses: 45,
        winRate: 66.4,
        totalMatches: 134,
        bestRank: 'Global Elite',
        currentRank: 'Global Elite',
        totalHours: 1240,
      },
    ],
    achievements: [
      {
        id: '1',
        name: 'First Blood',
        description: 'Win your first match',
        icon: '⚔️',
        unlockedDate: '2022-01-20',
        rarity: 'common',
      },
      {
        id: '2',
        name: 'Legendary',
        description: 'Reach 100 wins',
        icon: '👑',
        unlockedDate: '2022-06-15',
        rarity: 'epic',
      },
      {
        id: '3',
        name: 'Unstoppable',
        description: 'Win 10 consecutive matches',
        icon: '🔥',
        unlockedDate: '2023-02-28',
        rarity: 'rare',
      },
      {
        id: '4',
        name: 'Champion',
        description: 'Win a tournament',
        icon: '🏆',
        unlockedDate: '2023-08-10',
        rarity: 'legendary',
      },
      {
        id: '5',
        name: 'Multi-Game Master',
        description: 'Reach high rank in 3 different games',
        icon: '🎮',
        unlockedDate: '2024-01-22',
        rarity: 'legendary',
      },
    ],
    trophies: [
      {
        id: '1',
        title: 'World Championship',
        tournament: 'League of Legends Worlds 2023',
        date: '2023-11-19',
        placement: 1,
        prizeAmount: 5000,
      },
      {
        id: '2',
        title: 'Regional Finals',
        tournament: 'Valorant LAS Regional 2024',
        date: '2024-04-15',
        placement: 1,
        prizeAmount: 3000,
      },
      {
        id: '3',
        title: 'Runners-up',
        tournament: 'International Major 2024',
        date: '2024-06-22',
        placement: 2,
        prizeAmount: 2000,
      },
    ],
    friends: [
      { id: '2', nickname: 'ShadowNinja', avatar: '/placeholder-user.jpg', level: 38 },
      { id: '3', nickname: 'Phoenix', avatar: '/placeholder-user.jpg', level: 41 },
      { id: '4', nickname: 'Titan', avatar: '/placeholder-user.jpg', level: 35 },
      { id: '5', nickname: 'Apex', avatar: '/placeholder-user.jpg', level: 39 },
    ],
  },
  ShadowNinja: {
    id: '2',
    nickname: 'ShadowNinja',
    avatar: '/placeholder-user.jpg',
    bio: 'Casual competitive player | Valorant main',
    level: 38,
    totalXP: 98000,
    balance: 1200.25,
    totalEarnings: 8500.00,
    joinDate: '2022-03-22',
    gameStats: [
      {
        id: '1',
        game: 'Valorant',
        wins: 145,
        losses: 78,
        winRate: 65.0,
        totalMatches: 223,
        bestRank: 'Radiant',
        currentRank: 'Immortal',
        totalHours: 1840,
      },
    ],
    achievements: [
      {
        id: '1',
        name: 'First Blood',
        description: 'Win your first match',
        icon: '⚔️',
        unlockedDate: '2022-03-25',
        rarity: 'common',
      },
    ],
    trophies: [
      {
        id: '1',
        title: 'Runner-up',
        tournament: 'Valorant Cup 2024',
        date: '2024-02-20',
        placement: 2,
        prizeAmount: 1500,
      },
    ],
    friends: [
      { id: '1', nickname: 'ProGamer', avatar: '/placeholder-user.jpg', level: 42 },
    ],
  },
};

export const REGIONS = [
  'Global',
  'Norteamérica',
  'Centroamérica',
  'Sudamérica',
  'Europa',
  'Asia',
  'Oceanía',
  'África',
];

export const INPUT_TYPES = [
  'Mando',
  'Teclado y Ratón',
  'Todos',
];

export const TOURNAMENT_TYPES = [
  'Eliminación simple',
  'Doble eliminación',
  'Round Robin',
];

export const BEST_OF_OPTIONS = [1, 3, 5, 7];

export const FORMATS = [
  '1 contra 1',
  'Equipos 2v2',
  'Equipos 3v3',
  'Equipos 5v5',
];
